name = "Blio"
uuid = "87855aa7-8b24-49b4-b316-97c011f78d17"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.2.1"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
